### ISSUE TITLE
Error occurred when executing CLIP_Interrogator

### ISSUE THREAD

**Issue by teiteilingtei** [edenartlab/eden_comfy_pipelines#4]
expected str, bytes or os.PathLike object, not NoneType

File "G:\ComfyUI-aki-v1.1\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "G:\ComfyUI-aki-v1.1\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "G:\ComfyUI-aki-v1.1\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "G:\ComfyUI-aki-v1.1\custom_nodes\eden_comfy_pipelines\clip_utils\clip_tools.py", line 66, in interrogate
clip_model_dir = os.path.join(find_comfy_models_dir(), "clip")
File "G:\ComfyUI-aki-v1.1\python\lib\ntpath.py", line 104, in join
path = os.fspath(path)

**Comment by Pauweltje** [comment]
The error message `expected str, bytes or os.PathLike object, not NoneType` indicates an issue where a function expects a path as input but receives `None` instead. This typically occurs when a variable or a function meant to provide a path isn't set correctly or doesn't return a value.

In your case, it looks like the function `find_comfy_models_dir()` isn't returning a path, which could be because the model location isn't correctly defined or there's an issue with how the software tries to locate it.

To potentially resolve this issue, you might:
1. Check if configuration files defining the models' location are correctly set and in the right place.
2. Verify that the function `find_comfy_models_dir()` is working correctly by testing it separately to ensure it returns the expected directory path. (Chat-GPT4)

**Comment by filliptm** [comment]
bump

**Comment by aiXander** [comment]
This should be fixed with new way of importing folder_paths
